app:
  repository: ymlRepository
  filepath: classpath
  filename: questions.yml
#  repository: ymlRepository
#  filepath: filesystem
#  filename: d:/test/questions.yml
#  repository: csvRepository
#  filepath: filesystem
#  filename: d:/test/questions.csv
#  repository: csvRepository
#  filepath: classpath
#  filename: questions.csv

testing:
  points:
    min: 5